networks:
  database:
    external: true

services:
  whereq-mysql:
    image: mysql:8.0.32
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - /c/Users/googo/docker/volumes/mysql/mysql-files:/var/lib/mysql-files
      - /c/Users/googo/docker/volumes/mysql/log:/var/log/mysql
      - /c/Users/googo/docker/volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=whereq
      - MYSQL_ROOT_PASSWORD=123456
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    networks:
      - database
    ports:
      - 3306:3306
    command: mysqld --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  keycloak:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_ENABLED: true
        KC_HTTP_PORT: 8080
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_STRICT_HTTPS: false
        DEBUG: 'true'
        DEBUG_SUSPEND: 'y'
        DEBUG_PORT: '*:5005'
      ports:
#        - 8080:8080
        - 80:8080
        - 5005:5005
      volumes:
        - ./volumes/keycloak/conf:/opt/keycloak/conf
        - ./volumes/keycloak/providers:/opt/keycloak/providers
      command:
        - start-dev
      depends_on:
        - whereq-mysql
      networks:
        - database


